# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: define
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/server-snippets: |
      location /live {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
      }

  hosts:
    - host: integration-reports-sit.com.br
      paths:
        - path: /
          pathType: ImplementationSpecific
        - path: /live
          pathType: Prefix
          port: 4000
  tls:
    - secretName: secret-name
      hosts:
        - integration-reports-sit.com.br

resources:
  limits:
    cpu: 800m
    memory: 1000Mi
  requests:
    cpu: 600m
    memory: 800Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector:
  app: integration_report

tolerations: []

affinity: {}
